"""Compilagent — a lean, plug-and-play optimization core.

Phase-1 surface: contracts (`Backend`, `Harness`, `WorkloadSpec`, `Toolset`,
`ObservationSink`, `ArtifactRenderer`, `CandidatePolicy`), the canonical
`OptimizationSession` loop, and the storage / observation primitives. No
compiler, harness, or UI integrations live here — those plug in through
`compilagent.integrations.<name>` in Phase 2.
"""

from .bootstrap import (
    get_recent_load_failures,
    import_modules,
    load_entry_point_integrations,
)
from .core import (
    Analysis,
    Backend,
    BackendBase,
    BackendRegistry,
    BenchmarkBudget,
    BooleanFlag,
    CandidatePolicy,
    CompileResult,
    CorrectnessResult,
    DerivationEvidence,
    DeviceCapability,
    DtypePolicy,
    EnumChoice,
    FloatRange,
    Intervention,
    IntFreeform,
    IntRange,
    Lever,
    LeverRange,
    NullPolicy,
    Objective,
    ObjectiveGoal,
    PassEvent,
    Plan,
    PolicyHint,
    SearchSpace,
    SearchSpaceDerivation,
    ShapePolicy,
    StructuredJsonRange,
    Target,
    TimingResult,
    ToleranceConfig,
    ToolDecl,
    ValidationResult,
    WorkloadInstance,
    WorkloadKind,
    WorkloadSpec,
    backend_registry,
    register_workload,
    register_workload_safely,
    workload_registry,
)
from .harness import (
    Harness,
    HarnessRegistry,
    HarnessResult,
    HarnessRunRequest,
    StreamEvent,
    StreamEventKind,
    harness_registry,
)
from .observation import (
    ArtifactPreview,
    ArtifactRenderer,
    ArtifactRendererRegistry,
    CapturingSink,
    EventKind,
    NullSink,
    ObservationEvent,
    ObservationSink,
    artifact_renderer_registry,
)
from .session import OptimizationSession, build_session_toolset, run_session
from .settings import CompilagentSettings
from .storage import EpisodeStore, ExperimentLog, OptimizationWorkspace, TraceStore
from .toolset import Toolset

__all__ = [
    "Analysis",
    "ArtifactPreview",
    "ArtifactRenderer",
    "ArtifactRendererRegistry",
    "Backend",
    "BackendBase",
    "BackendRegistry",
    "BenchmarkBudget",
    "BooleanFlag",
    "CandidatePolicy",
    "CapturingSink",
    "CompilagentSettings",
    "CompileResult",
    "CorrectnessResult",
    "DerivationEvidence",
    "DeviceCapability",
    "DtypePolicy",
    "EnumChoice",
    "EpisodeStore",
    "EventKind",
    "ExperimentLog",
    "FloatRange",
    "Harness",
    "HarnessRegistry",
    "HarnessResult",
    "HarnessRunRequest",
    "IntFreeform",
    "IntRange",
    "Intervention",
    "Lever",
    "LeverRange",
    "NullPolicy",
    "NullSink",
    "Objective",
    "ObjectiveGoal",
    "ObservationEvent",
    "ObservationSink",
    "OptimizationSession",
    "OptimizationWorkspace",
    "PassEvent",
    "Plan",
    "PolicyHint",
    "SearchSpace",
    "SearchSpaceDerivation",
    "ShapePolicy",
    "StreamEvent",
    "StreamEventKind",
    "StructuredJsonRange",
    "Target",
    "TimingResult",
    "ToleranceConfig",
    "ToolDecl",
    "Toolset",
    "TraceStore",
    "ValidationResult",
    "WorkloadInstance",
    "WorkloadKind",
    "WorkloadSpec",
    "artifact_renderer_registry",
    "backend_registry",
    "build_session_toolset",
    "harness_registry",
    "get_recent_load_failures",
    "import_modules",
    "load_entry_point_integrations",
    "register_workload",
    "register_workload_safely",
    "run_session",
    "workload_registry",
]
